#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# generate-dashboard-cm.sh
# Reads monitoring/dashboards/platform-health.json and writes a proper
# Kubernetes ConfigMap YAML so the Grafana sidecar can auto-load it.
# Run this whenever you update the dashboard JSON.
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DASHBOARD_JSON="$REPO_ROOT/monitoring/dashboards/platform-health.json"
OUTPUT="$REPO_ROOT/k8s/base/monitoring/dashboard-configmap.yaml"

if [[ ! -f "$DASHBOARD_JSON" ]]; then
  echo "ERROR: $DASHBOARD_JSON not found"
  exit 1
fi

# Indent the JSON with 4 spaces for the ConfigMap data block
INDENTED=$(sed 's/^/    /' "$DASHBOARD_JSON")

cat > "$OUTPUT" <<EOF
# AUTO-GENERATED by scripts/generate-dashboard-cm.sh — do not edit manually.
# Re-run the script after updating monitoring/dashboards/platform-health.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-health-dashboard
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  platform-health.json: |-
$INDENTED
EOF

echo "✅  Written: $OUTPUT"
